name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Lint markdown
        uses: docker://ghcr.io/ponylang/shared-docker-ci-markdownlint:20260810

  lint-shell:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Lint shell scripts
        uses: docker://ghcr.io/ponylang/shared-docker-ci-shellcheck:20260810

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Verify CHANGELOG
        run: changelog-tool verify

  ubuntu-24_04:
    name: Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v6.0.2
      - name: Install Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '24.x'
          cache: 'npm'
      - name: Build
        run: make config=debug
      - name: Test
        run: xvfb-run -a make test
